#!/usr/bin/perl

=head1 NAME

matchedit - edit regions of files which match a regular expression

=head1 SYNOPSIS

B<matchedit>
[-I<CTNX>]
I<RE>
I<FILE>...

=head1 DESCRIPTION

B<matchedit> lets you edit all the regions of the specified files which match the regular expression I<RE> simultaenously.

=head1 LOG

  $Id: matchedit,v 1.8 2001/05/02 16:16:43 mah Exp $

  20000313 mah	first running version
  20000314 mah	use egrep instead of grep
  20000314 mah	program exit on no match
  20000314 mah	cmd line option for size of context presented
  20010115 mah	added perldoc
  20030206 mah	editor in $EDITOR
  TODO	customize bracket structure
  TODO	quoting of file names in grep call required

=head1 AUTHOR

Mark A. Hillebrand <mah@wjpserver.cs.uni-sb.de>

=head1 LEGAL

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=cut


$context = ($ARGV[0] =~ /^-\d$/ ? shift @ARGV : "-2" );

$re = quotemeta( shift @ARGV );

$FILE = "";
open( IF, "egrep $context -d skip -n -Z $re @ARGV /|" );
	# the '/' at the end forces my grep to prefix filenames even on single file input
	# the '-d skip' causes egrep to silently ignore the directory
	# the -Z option causes filenames to be terminated by \0 which simplifies parsing

die "Could not match anything" if eof( IF );
open( OF, "> .matchedit-$$" );
while( <IF> ) {
	last unless m/^(.*?)\0(\d+?)[:-](.*)/;
	$fn = $1;
	$from = $to = $2;
	$line = "$3\n";
	if( $FILE eq "" ) {
		print OF "FILE $fn\n"
	} else {
		print OF "FILEEND\nFILE $fn\n" unless $fn eq $FILE;
	}
	$FILE = $fn;
	while( <IF> ) {
		last if /^--/;
		$to++;
		m/^.*?\0\d+[:-](.*)/;
		$line .= "$1\n";
	}
	print OF "LINES $from-$to\n${line}LINESEND\n";
}
print OF "FILEEND\n" unless $FILE eq "";
close IF; close OF;

my $EDITOR = $ENV{EDITOR} || "vi";

system( "$EDITOR .matchedit-$$" );

print "Answer YES if you want the changes to take effect: ";
$choice = <STDIN>;

if( $choice eq "YES\n" ) {
	open( IF, "<.matchedit-$$" );
	while( <IF> ) {
		last unless m/^FILE (.*)/;
		$fn = $1;
		system( "mv $fn ${fn}.bak" );
		open( PROCIF, "<${fn}.bak" );
		open( OF, ">$fn" );
		while( <IF> ) {
			last unless m/^LINES (\d+)-(\d+)/;
			$from = $1;
			$to = $2;
			tell PROCIF;	# to initialize $.
			while( $. < $from - 1 ) {	# copy part before
			print OF scalar <PROCIF>;
		}
		while( $. < $to ) {	# dummy read the part
		<PROCIF>; 
	}
	while( <IF> ) { 	# paste in new lines
	last if /^LINESEND/; 
	print OF $_;
}
last if /^FILEEND/;
}
# must have read FILEEND on correct file structure
print OF <PROCIF>;	# copy rest of file

close PROCIF;
}
}

system( "rm .matchedit-$$" );
